version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: 7.4
        APP_ENV: development
        APP: maindata
        XDEBUG_CONFIG: 'idekey=PHPSTORM'
        NODE_ENV: development
        USER_ID: ${HOST_USER_ID}
        USER_GID: ${HOST_USER_GID}
    container_name: ${CONTAINER_NAME}
    image: app
    stdin_open: true
    tty: true
    depends_on:
      - db
      - mailhog
    networks:
      - app_network
    expose:
      - '9000'
    working_dir: /var/www/app
    environment:
      APP_ENV: development
      APP: maindata
      XDEBUG_CONFIG: 'idekey=PHPSTORM'
      XDEBUG_REMOTE_HOST: ${XDEBUG_HOST}
      NODE_ENV: development

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
        FLASK_ENV: development
        DEBIAN_FRONTEND: noninteractive
        USER_ID: ${HOST_USER_ID}
        USER_GID: ${HOST_USER_GID}
        HOST: ${HOST}
    image: ${CONTAINER_NAME}-nginx:1.0.0
    container_name: ${CONTAINER_NAME}_nginx
    hostname: ${HOST}
    domainname: ${HOST}
    working_dir: /var/www/app
    environment:
      APP_ENV: development
      HOST: ${HOST}
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    networks:
      app_network:
        aliases:
          - ${HOST}

  db:
    image: mysql:5.7
    container_name: "${CONTAINER_NAME}_db"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./assets/mysql/dump:/docker-entrypoint-initdb.d

  mailhog:
    image: mailhog/mailhog
    container_name: "${CONTAINER_NAME}_mailhog"
    ports:
      - ${SMTP_PORT}:1025
      - ${MAILHOG_PORT}:8025

  memcached:
    image: memcached:latest
    container_name: ${CONTAINER_NAME}_memcached
    networks:
      - app_network
    expose:
      - '11211'
      - '11212'

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '192.168.222.0/24'
